name: u_SAINT grade dispatch confirmation

on:
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install playwright
          playwright install
          pip install beautifulsoup4 slack_sdk python-dotenv

      - name: Run dispatch_confirmation.py
        env:
          ID: ${{ secrets.ID }}
          PASSWORD: ${{ secrets.PASSWORD }}
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
          GRADE_CHANNEL_ID: ${{ secrets.GRADE_CHANNEL_ID }}
        run: python u-saint_grade/dispatch_confirmation.py
